// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: i
func (_m *Logger) Debug(i ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, i...)
	_m.Called(_ca...)
}

// Fatal provides a mock function with given fields: i
func (_m *Logger) Fatal(i ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, i...)
	_m.Called(_ca...)
}

// Print provides a mock function with given fields: i
func (_m *Logger) Print(i ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, i...)
	_m.Called(_ca...)
}
