FROM golang:1.17-alpine as build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . /app

RUN go build -o "./bin/server" ./cmd/server

FROM alpine:3.15
WORKDIR /
COPY --from=build /app/bin/server /server
COPY ./data/quotes.csv /data/quotes.csv

ENTRYPOINT ["/server"]